# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8fab4df88027861422eca3c7417ae9f7"
name = "Discounting App"
application_url = "https://jeffrey-anaheim-cape-specifies.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "discountingapp-com.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://jeffrey-anaheim-cape-specifies.trycloudflare.com/auth/callback",
  "https://jeffrey-anaheim-cape-specifies.trycloudflare.com/auth/shopify/callback",
  "https://jeffrey-anaheim-cape-specifies.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
